// Generated by CoffeeScript 1.12.3

/*
 > ================================================================\
 >> @httpService
 > ================================================================/
 */

(function() {
  var http;

  http = function($http) {
    var that;
    lg("HTTP Service Initiated");
    that = this;
    this.sendHttpReq = function(reqUri, reqMethod, reqData, callBackFn) {
      $http({
        method: reqMethod,
        url: globalUrlBase + globalUrlPrefix + reqUri,
        headers: {
          'accept': 'application/json'
        },
        data: reqData
      }).then((function(response) {
        lg('GOT SuccessCallback');
        callBackFn(response);
      }), function(response) {
        lg('GOT ErrorCallback: ' + response.status);
        callBackFn(response);
      });
    };
  };

  angular.module('BoilerApp').service('http', http);

  http.$inject = ['$http'];

}).call(this);
