// Generated by CoffeeScript 1.12.6

/*
 > ================================================================\
 >> @MainModule
 > ================================================================/
 */

(function() {
  var hrApp;

  hrApp = angular.module('BoilerApp', ['ui.router', 'LocalStorageModule']);

  hrApp.config([
    '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
      lg("in hrApp.config");
      $urlRouterProvider.otherwise('main');
      $stateProvider.state('main', {
        url: '/main',
        templateUrl: 'views/main.component.html',
        controller: 'mainPageController'
      });
    }
  ]);

  hrApp.run([
    '$rootScope', '$location', '$state', '$http', '$templateCache', 'localStorageService', function($rootScope, $location, $state, $http, $templateCache, localStorageService) {
      lg("in hrApp.run");
      $rootScope.$on('$locationChangeStart', function(event, next, current) {});
      $rootScope.$on('$stateChangeSuccess', function(ev, to, toParams, from, fromParams) {});
      $rootScope.$on('$viewContentLoaded', function() {
        $templateCache.removeAll();
      });
    }
  ]);

  this.lg = function(message) {
    console.log(message);
  };

}).call(this);
